namespace Mirage.Shared;

/// <summary>Pure territory-income math: the weeks-held multiplier, the per-kill gold, and the
/// per-day accrual clamp. Kept side-effect-free so it is directly unit-testable and shared by the combat
/// accrual hook + the settlement credit.</summary>
public static class TerritoryFormulas
{
    /// <summary>Income multiplier for a territory held <paramref name="weeksHeld"/> consecutive weeks:
    /// 0 (fresh) -> x1, 1 -> x2, 2 -> x3, 3+ -> x<see cref="Constants.TerritoryWeeksHeldCap"/> (capped).</summary>
    public static int WeeksHeldMultiplier(int weeksHeld) =>
        Math.Clamp(weeksHeld, 0, Constants.TerritoryWeeksHeldCap - 1) + 1;

    /// <summary>Gold generated by one qualifying PvE kill: the owner base if the killer is in the owning
    /// guild, else the non-owner base, times the weeks-held multiplier.
    ///
    /// <para>Flat, to match the guild costs it funds. Scaling vault INCOME while the vault's costs stayed
    /// flat would just move the decay from one side of the guild economy to the other; the two halves are
    /// kept on the same footing deliberately.</para></summary>
    public static int IncomeForKill(bool killerInOwningGuild, int weeksHeld) =>
        (killerInOwningGuild ? Constants.TerritoryIncomeOwnerGold : Constants.TerritoryIncomeNonOwnerGold)
        * WeeksHeldMultiplier(weeksHeld);

    /// <summary>Add <paramref name="income"/> to the day's accumulator, clamped at the per-day cap
    /// (anti-snowball). Never exceeds <paramref name="dailyCap"/>.</summary>
    public static long AccruePending(long current, long income, long dailyCap) =>
        Math.Min(dailyCap, current + Math.Max(0, income));

    /// <summary>The next war-night slot at or after <paramref name="nowLocal"/> (server-local): the next
    /// occurrence of weekday <paramref name="day"/> at <paramref name="hour"/>:00. If today's slot has already
    /// passed, returns next week's. Pure (takes the clock in) so it's testable.</summary>
    public static DateTime NextWarNight(DateTime nowLocal, DayOfWeek day, int hour)
    {
        int daysAhead = ((int)day - (int)nowLocal.DayOfWeek + 7) % 7;
        var slot = nowLocal.Date.AddDays(daysAhead).AddHours(hour);
        return slot <= nowLocal ? slot.AddDays(7) : slot;
    }

    /// <summary>Resolve a war-night contest's winning guild: a present defender always holds (a 0-0 tie goes
    /// to the defender); with no defender (unclaimed or abandoned) a LONE claimant takes it, while 2+ claimants
    /// tie and it stays unclaimed. <paramref name="defenderId"/> is 0 when the territory is unclaimed or its
    /// owner abandoned it. Returns the new owner (0 = unclaimed). War kills are not scored, so a defended
    /// territory cannot currently be taken.</summary>
    public static int ResolveWinner(int defenderId, IReadOnlyList<int> challengers) =>
        defenderId > 0 ? defenderId : (challengers.Count == 1 ? challengers[0] : 0);
}
